const authenticationConstants = {
  "AUTH_CHECK_REQUEST": "AUTH_CHECK_REQUEST",
  "AUTH_CHECK_SUCCESS": "AUTH_CHECK_SUCCESS",
  "AUTH_CHECK_ERROR": "AUTH_CHECK_ERROR",

  "AUTH_LOGIN_REQUEST": "AUTH_LOGIN_REQUEST",
  "AUTH_LOGIN_SUCCESS": "AUTH_LOGIN_SUCCESS",
  "AUTH_LOGIN_ERROR": "AUTH_LOGIN_ERROR",

  "AUTH_LOGOUT_REQUEST": "AUTH_LOGOUT_REQUEST",
  "AUTH_LOGOUT_SUCCESS": "AUTH_LOGOUT_SUCCESS",
  "AUTH_LOGOUT_ERROR": "AUTH_LOGOUT_ERROR",


  "AUTH_SIGNUP_REQUEST": "AUTH_SIGNUP_REQUEST",
  "AUTH_SIGNUP_SUCCESS": "AUTH_SIGNUP_SUCCESS",
  "AUTH_SIGNUP_ERROR": "AUTH_SIGNUP_ERROR",

  "AUTH_GOOGLE_LOGIN_REQUEST": "AUTH_GOOGLE_LOGIN_REQUEST",
  "AUTH_GOOGLE_LOGIN_SUCCESS": "AUTH_GOOGLE_LOGIN_SUCCESS",
  "AUTH_GOOGLE_LOGIN_ERROR": "AUTH_GOOGLE_LOGIN_ERROR",
}

export default authenticationConstants