const movieConstants = {
  GET_MOVIE_BY_RATING: "GET_MOVIE_BY_RATING",
  GET_MOVIE_BY_RATING_SUCCESS: "GET_MOVIE_BY_RATING_SUCCESS",
  GET_MOVIE_BY_RATING_ERROR: "GET_MOVIE_BY_RATING_ERROR",

  GET_MOVIE_BY_DAY: "GET_MOVIE_BY_DAY",
  GET_MOVIE_BY_DAY_SUCCESS: "GET_MOVIE_BY_DAY_SUCCESS",
  GET_MOVIE_BY_DAY_ERROR: "GET_MOVIE_BY_DAY_ERROR",

  GET_MOVIE_BY_RECOMMEND: "GET_MOVIE_BY_RECOMMEND",
  GET_MOVIE_BY_RECOMMEND_SUCCESS: "GET_MOVIE_BY_RECOMMEND_SUCCESS",
  GET_MOVIE_BY_RECOMMEND_ERROR: "GET_MOVIE_BY_RECOMMEND_ERROR",

  GET_MOVIE_BY_YEAR: "GET_MOVIE_BY_YEAR",
  GET_MOVIE_BY_YEAR_SUCCESS: "GET_MOVIE_BY_YEAR_SUCCESS",
  GET_MOVIE_BY_YEAR_ERROR: "GET_MOVIE_BY_YEAR_ERROR",

  GET_MOVIE_BY_RANDOM: "GET_MOVIE_BY_RANDOM",
  GET_MOVIE_BY_RANDOM_SUCCESS: "GET_MOVIE_BY_RANDOM_SUCCESS",
  GET_MOVIE_BY_RANDOM_ERROR: "GET_MOVIE_BY_RANDOM_ERROR",

  GET_MOVIE_BY_GENRES: "GET_MOVIE_BY_GENRES",
  GET_MOVIE_BY_GENRES_SUCCESS: "GET_MOVIE_BY_GENRES_SUCCESS",
  GET_MOVIE_BY_GENRES_ERROR: "GET_MOVIE_BY_GENRES_ERROR",

  GET_MOVIE_BY_KEYWORD: "GET_MOVIE_BY_KEYWORD",
  GET_MOVIE_BY_KEYWORD_SUCCESS: "GET_MOVIE_BY_KEYWORD_SUCCESS",
  GET_MOVIE_BY_KEYWORD_ERROR: "GET_MOVIE_BY_KEYWORD_ERROR",

  GET_MOVIE_BY_COMING: "GET_MOVIE_BY_COMING",
  GET_MOVIE_BY_COMING_SUCCESS: "GET_MOVIE_BY_COMING_SUCCESS",
  GET_MOVIE_BY_COMING_ERROR: "GET_MOVIE_BY_COMING_ERROR",

  GET_DETAIL_MOVIE: "GET_DETAIL_MOVIE",
  GET_DETAIL_MOVIE_SUCCESS: "GET_DETAIL_MOVIE_SUCCESS",
  GET_DETAIL_MOVIE_ERROR: "GET_DETAIL_MOVIE_ERROR",

  GET_RELATED_MOVIE: "GET_RELATED_MOVIE",
  GET_RELATED_MOVIE_SUCCESS: "GET_RELATED_MOVIE_SUCCESS",
  GET_RELATED_MOVIE_ERROR: "GET_RELATED_MOVIE_ERROR",
}

export default movieConstants;