export const reportConstants = {
    GET_REPORTS: "GET_REPORTS",
    GET_REPORTS_SUCCESS: "GET_REPORTS_SUCCESS",
    GET_REPORTS_ERROR: "GET_REPORTS_ERROR",

    GET_REPORT: "GET_REPORT",
    GET_REPORT_SUCCESS: "GET_REPORT_SUCCESS",
    GET_REPORT_ERROR: "GET_REPORT_ERROR",
}