const userConstants = {
  GET_USER_REQUEST: "GET_USER_REQUEST",
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
  GET_USER_ERROR: "GET_USER_ERROR",

  CLEAR_USER_REQUEST: "CLEAR_USER_REQUEST",
  CLEAR_USER_SUCCESS: "CLEAR_USER_SUCCESS",
  CLEAR_USER_ERROR: "CLEAR_USER_ERROR",
}

export default userConstants;