export enum BaseAction {
  CREATE="CREATE",
  UPDATE="UPDATE",
  DELETE="DELETE",
  "GET.BY_ID"="GET.BY_ID",
}
export type BaseActionUnion = keyof typeof BaseAction

export enum EntityKey { 
  USER="USER", 
  MOVIE="MOVIE", 
  GENRE="GENRE",
}
export type EntityKeyUnion = keyof typeof EntityKey

export type BasePattern<key extends EntityKeyUnion> = {
  [action in BaseActionUnion]: `${key}.${action}` 
}[BaseAction]

export type GenrePattern = BasePattern<"GENRE"> | "GENRE.GET.ALL"

export type MoviePattern = BasePattern<"MOVIE"> | 
  "MOVIE.GET.BY_YEAR" | "MOVIE.GET.BY_RATING" | "MOVIE.GET.BY_GENRES" | 
  "MOVIE.GET.BY_DAY" | "MOVIE.GET.BY_SEARCH" | "MOVIE.GET.BY_UPCOMING" |
  "MOVIE.GET.BY_RANDOM" | "MOVIE.GET.BY_RANDOM_BACKDROP";

export type AuthPattern = "AUTH.LOGIN" | "AUTH.REGISTER" | "AUTH.VALIDATE" | "AUTH.GOOGLE_LOGIN" | "AUTH.REFRESH_TOKEN"

export type UserPattern = BasePattern<"USER"> | 
  "USER.GET.BY_EMAIL" | "USER.CREATE.BY_GOOGLE" | "USER.CHECK.BY_EMAIL" | 
  "USER.GET.BY_EMAIL_AND_PASSWORD" | "USER.UPDATE.PASSWORD"

export type Pattern = UserPattern | MoviePattern  | AuthPattern | GenrePattern

export type PatternOptionType = {
  [T in Pattern]: `${T}`
}

export const PatternOption: PatternOptionType = {
  // USER
  "USER.CREATE": "USER.CREATE",
  "USER.UPDATE": "USER.UPDATE",
  "USER.DELETE": "USER.DELETE",
  "USER.GET.BY_ID": "USER.GET.BY_ID",
  "USER.CREATE.BY_GOOGLE": "USER.CREATE.BY_GOOGLE",
  "USER.GET.BY_EMAIL": "USER.GET.BY_EMAIL",
  "USER.CHECK.BY_EMAIL": "USER.CHECK.BY_EMAIL",
  "USER.GET.BY_EMAIL_AND_PASSWORD": "USER.GET.BY_EMAIL_AND_PASSWORD",

  "USER.UPDATE.PASSWORD": "USER.UPDATE.PASSWORD",

  // MOVIE
  "MOVIE.CREATE": "MOVIE.CREATE",
  "MOVIE.UPDATE": "MOVIE.UPDATE",
  "MOVIE.DELETE": "MOVIE.DELETE",
  "MOVIE.GET.BY_ID": "MOVIE.GET.BY_ID",
  "MOVIE.GET.BY_DAY": "MOVIE.GET.BY_DAY",
  "MOVIE.GET.BY_YEAR": "MOVIE.GET.BY_YEAR",
  "MOVIE.GET.BY_GENRES": "MOVIE.GET.BY_GENRES",
  "MOVIE.GET.BY_RATING": "MOVIE.GET.BY_RATING",
  "MOVIE.GET.BY_SEARCH": "MOVIE.GET.BY_SEARCH",
  "MOVIE.GET.BY_RANDOM": "MOVIE.GET.BY_RANDOM",
  "MOVIE.GET.BY_UPCOMING": "MOVIE.GET.BY_UPCOMING",
  "MOVIE.GET.BY_RANDOM_BACKDROP": "MOVIE.GET.BY_RANDOM_BACKDROP",

  // AUTH
  "AUTH.LOGIN": "AUTH.LOGIN",
  "AUTH.REGISTER": "AUTH.REGISTER",
  "AUTH.VALIDATE": "AUTH.VALIDATE",
  "AUTH.GOOGLE_LOGIN": "AUTH.GOOGLE_LOGIN",
  "AUTH.REFRESH_TOKEN": "AUTH.REFRESH_TOKEN",

  // GENRE
  "GENRE.CREATE": "GENRE.CREATE",
  "GENRE.UPDATE": "GENRE.UPDATE",
  "GENRE.DELETE": "GENRE.DELETE",
  "GENRE.GET.ALL": "GENRE.GET.ALL",
  "GENRE.GET.BY_ID": "GENRE.GET.BY_ID",
}
