export enum Service {
  AUTH = "AUTH-SERVICE",
  USER = "USER-SERVICE",
  MOVIE = "MOVIE-SERVICE",
  GENRE = "GENRE-SERVICE",
  REPORT = "REPORT-SERVICE",
  RECOMMENDATION = "RECOMMENDATION-SERVICE",
}